name: mango_ui
version: 1.0.3
description: MangoUI holds modules commonly used throughout Mango applications.
repository: https://github.com/louisevanderlith/mango-ui
homepage: https://github.com/louisevanderlith/mango-ui
environment:
  sdk: '>=2.0.0 < 3.0.0'