name: mango_ui
version: 0.2.1
description: MangoUI holds modules commonly used throughout Droxolite applications.
author: Louise van der Lith <louise@avosa.co.za>
repository: https://github.com/louisevanderlith/mango-ui
homepage: https://github.com/louisevanderlith/mango-ui
environment:
  sdk: '>=2.0.0 < 3.0.0'